<?php

namespace App\DemoBundle\Entity;

/**
 * InstitutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitutRepository extends \Doctrine\ORM\EntityRepository
{
}
